[2025-08-30T22:19:13.917+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dataset_ingestion.create_directories manual__2025-08-30T22:17:32.950490+00:00 [queued]>
[2025-08-30T22:19:13.923+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dataset_ingestion.create_directories manual__2025-08-30T22:17:32.950490+00:00 [queued]>
[2025-08-30T22:19:13.923+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2025-08-30T22:19:13.937+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): create_directories> on 2025-08-30 22:17:32.950490+00:00
[2025-08-30T22:19:13.940+0000] {standard_task_runner.py:57} INFO - Started process 207 to run task
[2025-08-30T22:19:13.944+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dataset_ingestion', 'create_directories', 'manual__2025-08-30T22:17:32.950490+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_ingestion_dag.py', '--cfg-path', '/tmp/tmp226dw5z5']
[2025-08-30T22:19:13.946+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask create_directories
[2025-08-30T22:19:13.986+0000] {task_command.py:416} INFO - Running <TaskInstance: kaggle_dataset_ingestion.create_directories manual__2025-08-30T22:17:32.950490+00:00 [running]> on host c9caace5c1c2
[2025-08-30T22:19:14.053+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='kaggle_dataset_ingestion' AIRFLOW_CTX_TASK_ID='create_directories' AIRFLOW_CTX_EXECUTION_DATE='2025-08-30T22:17:32.950490+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-30T22:17:32.950490+00:00'
[2025-08-30T22:19:14.054+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-30T22:19:14.054+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'mkdir -p /opt/***/data/raw/datasets/titanic && chmod -R 777 /opt/***/data/raw']
[2025-08-30T22:19:14.069+0000] {subprocess.py:86} INFO - Output:
[2025-08-30T22:19:14.073+0000] {subprocess.py:93} INFO - mkdir: cannot create directory ‘/opt/***/data/raw/datasets/titanic’: Permission denied
[2025-08-30T22:19:14.073+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-30T22:19:14.084+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-30T22:19:14.086+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=kaggle_dataset_ingestion, task_id=create_directories, execution_date=20250830T221732, start_date=20250830T221913, end_date=20250830T221914
[2025-08-30T22:19:14.098+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task create_directories (Bash command failed. The command returned a non-zero exit code 1.; 207)
[2025-08-30T22:19:14.115+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-08-30T22:19:14.134+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
